### ISSUE TITLE
the code for model

### ISSUE THREAD

**Issue by czhxiaohuihui** [furkanbiten/GoodNews#4]
Have you released the code for the model?

**Comment by furkanbiten** [comment]
I forgot to add, now it is there. 
Sorry, I forgot about it.

**Comment by raoanonymous** [comment]
@furkanbiten Thanks for sharing the awesome work! But is it possible to share the pre-trained models?

**Comment by furkanbiten** [comment]
Hi there,

Thanks for the kind words.

I uploaded 3 models to my Drive, they might require some extra processing,
sorry for that in advance.
AVG:
https://drive.google.com/open?id=1BD6Q8Xq1jQHmDHfAJcj6JDv7tEzjQBa_

WAVG:
https://drive.google.com/open?id=1FvzCmvFlPr9w60MPYuYzsDeJfZGOa7oy

TBB:
https://drive.google.com/open?id=14330P4RdknY2FpT7amtiRzA-rteJWdn9
